#!/bin/sh

bspc config window_gap $(($SCREEN_WIDTH / 85))
bspc config border_width 6
bspc config split_ratio 0.5

bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config focus_by_distance true
bspc config focus_follows_pointer true
bspc config auto_cancel true

bspc config focused_border_color "#6b615b"
bspc config normal_border_color "#302f2b"
bspc config active_border_color "#817267"
bspc config presel_border_color "#c0a08b"

bspc monitor -d 1 2 3 4

bspc rule -a urxvt-launcher floating=on

panel &
