#!/bin/sh

bspc config window_gap 40
bspc config border_width 6
bspc config split_ratio 0.5

bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config focus_by_distance true
bspc config focus_follows_pointer true

bspc config normal_border_color "#414041"
bspc config urgent_border_color "#414041"
bspc config focused_border_color "#645f5b"
bspc config presel_border_color "#c0a08b"

bspc monitor -d 1 2 3 4

bspc rule -a urxvt-launcher state=floating

panel &
