#!/bin/bash
#
# Install dotfiles.

dir="$(cd "$(dirname "$0")" && pwd)"
files="$(ls "${dir}")"
ignore="README.md install"

for file in $ignore; do
  files="${files/"$file"}"
done

for file in $files; do
  printf "\e[32m${dir/\/home\/*\//\~/}/${file} -> ~/.${file}\e[m\n"
  ln -snf "${dir}/${file}" "${HOME}/.${file}"
done
