#!/bin/bash
#
# dotfiles installer

dir="$(cd "$(dirname "$0")" && pwd)"
files="$(cd "${dir}" && echo *)"
ignore=(README.md install)

for file in ${ignore}; do
  files="${files/$file}"
done

for file in ${files}; do
  echo -e "\E[40;32m${dir}/${file} -> ${HOME}/.${file}\E[0m"
  ln -snf "${dir}/${file}" "${HOME}/.${file}"
done
